name: Sync to Hugging Face hub
on:
  push:
    branches: [master]
  workflow_dispatch:

jobs:
  sync-to-hub:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - name: Push to hub
        env:
          HF_TOKEN: ${{ secrets.HF_TOKEN }}
        run: |
          rm -rf .git
          git init
          git branch -M master
          git add .
          git config user.name "github-actions"
          git config user.email "github-actions@github.com"
          git commit -m "Initial sync without history"
          git push --force https://Sonal-888:$HF_TOKEN@huggingface.co/spaces/Sonal-888/my-video-studio master
